version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 8
    commands:
      - echo "install step"
      - npm install
  build:
    commands:
      - npm run build
      - npm run devDeploy
  post_build:
    commands:
      # TODO: should these have the same dist id?
      - aws cloudfront create-invalidation --distribution-id "${DISTRIBUTION_ID}" --paths '/*'
